### ISSUE TITLE
Feature request: add translator to the "Slug" field

### ISSUE THREAD

**Issue by PrimozRome** [voorhoede/datocms-plugin-translate-fields#34]
It would be good to have support for your plugin on Slug field types... We are translating all slugs into local languages, so this would be useful for us... Ty

**Comment by velomovies** [comment]
Hi @PrimozRome, we will look into this addition. Slug fields are complicated since text is always slugified. So we need to check if we can de-slugify the text, send that to the translation service and slugify the text again afterward. 

We will keep you posted if anything is added or we come accross other errors

**Comment by velomovies** [comment]
We've added the support in https://github.com/voorhoede/datocms-plugin-translate-fields/pull/37

This will be available in `v1.10.0`
